meta_product_name: "Spry"
meta_title: "Spry - the app that wants to get you out."
meta_description: "Spry connects thousands of athletic people like you to practice your favorite sport together."
meta_image: "cover.png" # should exist in `app/assets/images/`
